version: '3'
services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - '8081'
    expose:
      - '8081'
    restart: always

  redis-server:
    image: redis
    ports:
      - '6379:6379'
    restart: always

  # zookeeper-server:
  #   image: zookeeper
  #   ports:
  #     - '2181:2181'
  #   restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-server
    ports:
      - '4000:80'