version: '3'
services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - '8081'
    depends_on:
      - postgres
    expose:
      - '8081'
    restart: always

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    # environment:
    #   - POSTGRES_USER='postgres'
    #   - POSTGRES_PASSWORD='postgres'
      # - POSTGRES_DB=
    restart: always

  # redis-server:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  #   restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-server
    ports:
      - '4000:80'